// <auto-generated />
using System;
using InchirieriCaseteVideo.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InchirieriCaseteVideo.Migrations
{
    [DbContext(typeof(InchirieriDbContext))]
    [Migration("20200528203107_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("InchirieriCaseteVideo.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNastere")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenume")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("IdClient");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("InchirieriCaseteVideo.Models.FilmInchiriat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InchiriereCodTranzactie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titlu")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InchiriereCodTranzactie");

                    b.ToTable("FilmInchiriat");
                });

            modelBuilder.Entity("InchirieriCaseteVideo.Models.Inchiriere", b =>
                {
                    b.Property<int>("CodTranzactie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataTranzactie")
                        .HasColumnType("TEXT");

                    b.Property<int>("idClient")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("sfarsitPerioada")
                        .HasColumnType("TEXT");

                    b.HasKey("CodTranzactie");

                    b.ToTable("Inchierieri");
                });

            modelBuilder.Entity("InchirieriCaseteVideo.Models.FilmInchiriat", b =>
                {
                    b.HasOne("InchirieriCaseteVideo.Models.Inchiriere", null)
                        .WithMany("filmeInchiriate")
                        .HasForeignKey("InchiriereCodTranzactie");
                });
#pragma warning restore 612, 618
        }
    }
}
